steps:
- name: 'gcr.io/$PROJECT_ID/cloud-builder-gradle:4.10.2-jdk-8'
  entrypoint: 'bash'
  args: ['./gradlew', 'build']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - '--'
  - '
    set -e;
    [[ "$BRANCH_NAME" == "master" ]] && docker build -t "gcr.io/$PROJECT_ID/$REPO_NAME:latest" . && docker push "gcr.io/$PROJECT_ID/$REPO_NAME:latest";
    [[ -n "$TAG_NAME" ]] && docker build -t "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME" --build-arg "JAR_NAME=$REPO_NAME-$TAG_NAME.jar" . && docker push "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME";
    [[ "$BRANCH_NAME" == "master" || -n "$TAG_NAME" ]]
    '
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - '--'
  - '
    set -e;
    [[ -n "$TAG_NAME" ]] && /builder/kubectl.bash set image deployment $REPO_NAME "$REPO_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME" || echo "skipping deployment because \$$TAG_NAME is empty. . ."
    '
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dev-20181007'
