/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jkaldon' at '2/19/17 5:17 PM' with Gradle 3.1
 *
 * @author jkaldon, @date 2/19/17 5:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
